#import "Notifications.h"

NSString *const BLUETOOTH_SEARCHING = @"BLUETOOTH_SEARCHING";
NSString *const BLUETOOTH_CONNECTED = @"BLUETOOTH_CONNECTED";
NSString *const BLUETOOTH_DISCONNECTED = @"BLUETOOTH_DISCONNECTED";
NSString *const FOOHID_MISSING = @"FOOHID_MISSING";
