fastlane_version "2.62.1"

default_platform :mac

platform :mac do
  before_all do
    carthage
  end

  desc "Build"
  lane :build do
    gym
  end

  desc "Package"
  lane :package do
    `rm -r ../build/*`
    gym
    `cd ../build && create-dmg "./OpenTX BLE Joystick.app"`
  end

  desc "Version"
  lane :version do
    `agvtool bump -all`
  end
end
